# Generated by Django 3.2.9 on 2021-11-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probleminfo',
            name='ProblemMemLimit',
            field=models.IntegerField(verbose_name='空间限制'),
        ),
        migrations.AlterField(
            model_name='probleminfo',
            name='ProblemTimeLimit',
            field=models.IntegerField(verbose_name='时间限制'),
        ),
    ]
