# Generated by Django 3.2.9 on 2021-11-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_table', '0002_auto_20211109_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptsInfo',
            fields=[
                ('AttemptID', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.IntegerField(verbose_name='用户ID')),
                ('ProblemId', models.IntegerField(verbose_name='题目ID')),
                ('SourceCode', models.CharField(max_length=100000, verbose_name='源代码')),
                ('TestResult', models.CharField(max_length=100, verbose_name='测试结果')),
                ('TimeCost', models.IntegerField(verbose_name='使用时间')),
                ('MemCost', models.IntegerField(verbose_name='使用空间')),
                ('AttemptTime', models.DateTimeField(verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '提交信息',
                'verbose_name_plural': '提交信息',
                'db_table': 'attempt_Info',
            },
        ),
    ]
