# Generated by Django 3.2.9 on 2021-11-15 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_table', '0004_matchinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptsinfo',
            name='AttemptID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='attemptsinfo',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_table.userinfo'),
        ),
    ]
