# Generated by Django 3.2.9 on 2021-11-15 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_table', '0005_auto_20211115_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptsinfo',
            name='ProblemId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_table.probleminfo', verbose_name='题目ID'),
        ),
    ]
