# Generated by Django 3.2.9 on 2021-11-15 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_table', '0007_auto_20211115_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='uid',
            new_name='UserId',
        ),
        migrations.AlterField(
            model_name='attemptsinfo',
            name='AttemptID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attemptsinfo',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_table.userinfo', verbose_name='用户ID'),
        ),
        migrations.CreateModel(
            name='Problem_Match_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_table.matchinfo')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_table.probleminfo')),
            ],
            options={
                'verbose_name': '比赛题目',
                'db_table': 'Problem_Match',
            },
        ),
        migrations.CreateModel(
            name='User_Match_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_table.matchinfo')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_table.userinfo')),
            ],
            options={
                'verbose_name': '比赛人员',
                'verbose_name_plural': '比赛人员',
                'db_table': 'User_Match',
                'unique_together': {('User', 'Match')},
            },
        ),
    ]
