# Generated by Django 3.2.9 on 2021-11-15 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_table', '0008_auto_20211115_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem_match_info',
            options={'verbose_name': '比赛题目', 'verbose_name_plural': '比赛题目'},
        ),
    ]
