# Generated by Django 3.2.9 on 2021-12-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_table', '0012_alter_user_match_info_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='upasswd',
            field=models.CharField(max_length=30, verbose_name='密码md5'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_name',
            field=models.CharField(max_length=20, verbose_name='用户名称'),
        ),
    ]
